package main

import (
	"encoding/json"
	"fmt"
	"net/http"
	"strconv"

	"github.com/gorilla/mux"
)

/*
	IMPORTANT NOTE:

	1. This program was not generated by LLMs but I did use their help.
	   For that reason, I decided to include the AI parts as well.
	   This includes the points part and the error message in api.yml.
	2. To run, make sure to 'go install github.com/gorilla/mux' and go get it afterwards
	3. Then just run go run *.go
*/

func defaultHandler(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusOK)
	w.Write([]byte("Fetch rewards rocks!\nUsage:\n1. /receipts/process as POST with json data to get id\n2. /receipts/{id}/points to get the points associated with id"))
}

func processReceiptHandler(w http.ResponseWriter, r *http.Request) {
	var receipt Receipt
	err := json.NewDecoder(r.Body).Decode(&receipt)
	if err != nil {
		http.Error(w, badRequest, http.StatusBadRequest)
		return
	}

	fmt.Printf("Received receipt: %+v\n", receipt) //For Debugging purposes
	id := strconv.Itoa(generateID())               //Create new Id
	memory[id] = receipt                           //Insert to memory

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	json.NewEncoder(w).Encode(map[string]string{"id": id})
}

func getPointsHandler(w http.ResponseWriter, r *http.Request) {
	//Get id
	vars := mux.Vars(r)
	id := vars["id"]

	fmt.Printf("Calculating for ID: %s\n", id) //Debugging purposes

	//Check if the id has been assigned before and get the receipt that corresponds to it
	receipt, found := memory[id]
	if !found {
		http.Error(w, notFound, http.StatusNotFound)
		return
	}

	fmt.Printf("Calculating for receipt: %+v\n", receipt)

	points := calcPoints(receipt)
	fmt.Printf("Points calculated: %f\n", points)

	//calcPoints returns < 0 if there is an error
	if points < 0 {
		http.Error(w, badRequest, http.StatusBadRequest)
		return
	}

	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(http.StatusOK)

	json.NewEncoder(w).Encode(map[string]int{"points": int(points)})
}
